name: Build CMake Project and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build
      
    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest

